import type { Metadata } from "next";
import { ThemeProvider } from "@/components/provider/theme";
import { inter } from "@/components/provider/font";

import "./globals.css";

export const metadata: Metadata = {
  title: {
    template: "%s | Next App",
    default: "Next App",
  },
  applicationName: "Next App",
  description: "Generated by create next app.",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={inter.variable}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
