import type { Metadata } from "next";
import { ThemeProvider } from "@/components/provider/theme";
import { Toaster as ReactHotToaster } from "react-hot-toast";
import { SessionProvider } from "next-auth/react";

import { auth } from "@/auth/auth";
import { inter } from "@/components/provider/font";

import "./globals.css";

export const metadata: Metadata = {
  title: {
    template: "%s | Aoeri Next App",
    default: "Aoeri Next App",
  },
  applicationName: "Aoeri Next App",
  description: "Generated by create ioeri next app.",
  category: "Personal Platform",
  manifest: "/manifest.json",
  generator: "aoeri",
  publisher: "aoeri",
  referrer: "origin-when-cross-origin",
  keywords: ["aoeri", "ioeri", "original"],
  creator: "Ilham Khoeri - aoeri",
  authors: [{ name: "aoeri" }, { name: "Khoeri Ilham", url: "https://github.com/ioeridev" }],
};

export const viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "white" },
    { media: "(prefers-color-scheme: dark)", color: "black" },
  ],
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="en" suppressHydrationWarning>
        <head>
          <link rel="icon" sizes="any" href="/favicon.ico" />
          <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
          <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
          <link rel="shortcut icon" href="/favicon.ico" />
        </head>
        <body className={inter.variable}>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
            {children}

            <ReactHotToaster
              position="bottom-right"
              reverseOrder={false}
              gutter={8}
              containerClassName=""
              containerStyle={{ bottom: "32px", right: "40px" }}
              toastOptions={{
                className: "[&_.go3958317564]:inline",
                duration: 5000,
                style: {
                  background: "hsl(212deg 100% 48%)",
                  color: "white",
                  minWidth: "250px",
                },
                success: {
                  duration: 3000,
                },
                custom: {
                  style: { backgroundColor: "red" },
                },
              }}
            />
          </ThemeProvider>
        </body>
      </html>
    </SessionProvider>
  );
}
