import type { Metadata } from "next";
import { ThemeProvider } from "@/components/provider/theme";
import { Toaster } from "@/components/assets/toast/toaster";
import { SessionProvider } from "next-auth/react";

import { auth } from "@/auth/auth";
import { inter } from "@/components/provider/font";

import "./globals.css";
import { NavigationProgress } from "@/components/assets/navigation/progress";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: {
    template: "%s | Aoeri Next App",
    default: "Aoeri Next App",
  },
  applicationName: "Aoeri Next App",
  description: "Generated by create ioeri next app.",
  category: "Personal Platform",
  manifest: "/manifest.json",
  generator: "aoeri",
  publisher: "aoeri",
  referrer: "origin-when-cross-origin",
  keywords: ["aoeri", "ioeri", "original"],
  creator: "Ilham Khoeri - aoeri",
  authors: [{ name: "aoeri" }, { name: "Khoeri Ilham", url: "https://github.com/ioeridev" }],
};

export const viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "white" },
    { media: "(prefers-color-scheme: dark)", color: "black" },
  ],
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="en" suppressHydrationWarning>
        <head>
          <link rel="icon" sizes="any" href="/favicon.ico" />
          <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
          <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
          <link rel="shortcut icon" href="/favicon.ico" />
        </head>
        <body className={inter.variable}>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
            <Suspense fallback={null}>
              <NavigationProgress />
            </Suspense>
            {children}
            <Toaster />
          </ThemeProvider>
        </body>
      </html>
    </SessionProvider>
  );
}
